#!/bin/bash
# Enter a network namespace and set up the environment
# Usage: sudo ./enter [client|server|mitm]

NS=$1

case $NS in
    client)
        NSNAME="ns_client"
        HOMEDIR="/home/client"
        ROOTDIR="$(pwd)/client_root"
        ;;
    server)
        NSNAME="ns_server"
        HOMEDIR="/home/server"
        ROOTDIR="$(pwd)/server_root"
        ;;
    mitm)
        NSNAME="ns_mitm"
        HOMEDIR="/home/mitm"
        ROOTDIR="$(pwd)/mitm_root"
        ;;
    *)
        echo "Usage: $0 [client|server|mitm]"
        exit 1
        ;;
esac

exec ip netns exec $NSNAME unshare --mount bash --rcfile /dev/null -c "
    mount --bind $ROOTDIR /
    cd $HOMEDIR
    HOME=$HOMEDIR exec bash --norc
"
